import { CompanyAccount } from './class/CompanyAccount'
import { ExclusiveAccount } from './class/exclusiveAccount'
import { PeopleAccount } from './class/PeopleAccount'

const peopleAccount: PeopleAccount = new PeopleAccount(1, 'Nath', 10)
let name = peopleAccount.getName()
let numberCount = peopleAccount.getAccountNumber()
let valid = peopleAccount.getValidateStatus()
console.log("-----------------------------------------------------")
console.log("Classe PeopleAccount")
console.log("Nome:", name, "\nConta: ", numberCount, "\nStatus da conta: ", valid)
peopleAccount.deposit(200)
peopleAccount.setWithdraw(150)
let balance = peopleAccount.getBalance()
console.log(`Saldo da conta R$ ${(balance).toFixed(2).replace('.', ',')}`)
console.log("-----------------------------------------------------")
const companyAccount: CompanyAccount = new CompanyAccount('DIO', 20)
name = companyAccount.getName()
numberCount = companyAccount.getAccountNumber()
valid = companyAccount.getValidateStatus()
console.log("Classe CompanyAccount")
console.log("Nome:", name, "\nConta: ", numberCount, "\nStatus da conta: ", valid)
companyAccount.setLoan(100)
balance = companyAccount.getBalance()
console.log(`Saldo da conta R$ ${(balance).toFixed(2).replace('.', ',')}`)
console.log("-----------------------------------------------------")
const exclusiveAccount: ExclusiveAccount = new ExclusiveAccount('Bond', 40)
console.log("Classe ExclusiveAccount")
console.log("Nome:", name, "\nConta: ", numberCount, "\nStatus da conta: ", valid)
exclusiveAccount.deposit(100)
balance = exclusiveAccount.getBalance()
console.log(`Saldo da conta R$ ${(balance).toFixed(2).replace('.', ',')}`)
console.log("-----------------------------------------------------")
//console.log(exclusiveAccount)